//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuoiCuaHangCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        public int MABAN { get; set; }
        public string MADH { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
